language: Swift
osx_image: xcode9.1
xcode_project: CoreNetKit.xcodeproj # path to your xcodeproj folder
xcode_scheme: CoreNetKit
before_install:
  - gem install xcpretty -N
  - brew update
  - brew install swiftlint || true
script:
  - set -o pipefail
