os: osx
osx_image: xcode10.2
language: obj-c

before_install:
  - pod install --repo-update
  - gem install xcpretty -N
  - gem install jazzy

jobs:
  include:
    - stage: build_stage
      name: Build stage
      script: xcodebuild -workspace NodeKit.xcworkspace -scheme NodeKit
    - stage: test_prepare
      name: Prepare environment for testing
      script: 
      - sh ci/prepare_srv_deploy.sh
      - sh ci/prepare_tests.sh

    - stage: test_deploy
      name: Deploy TestServer
      script: sh ci/deploy_server.sh
      
    - stage: test
      name: Testing
      script: 
        - sh ci/run_tests.sh
        - sh ci/codecov_report.sh

    - stage: test_reporting
      name: Report test results
    - script: ci/codecov_report.sh
      name: Deploy CodeCov Report
    - stage: docs

    # - stage: docks_gen
    #   name: Generate Documentation
    #   script: ci/docks/dock_gen.sh

    # - stage: docks_deploy
    #   name: Deploy Documentation 
    #   script: ci/docks/deploy_docs.sh
