language: swift
osx_image: xcode10.1
xcode_project: CoreNetKit.xcworkspace
xcode_scheme: CoreNetKit
before_install:
  - pod install --repo-update
  - gem install xcpretty -N
  - brew update
  - gem install jazzy
  - brew install swiftlint || true
after_script:
  - set -o pipefail
  #- setsid TestServer/bin/TestServer
  #- xcodebuild test -scheme CoreNetKitIntegrationTests -configuration "Debug" -sdk iphonesimulator -enableCodeCoverage YES -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.4' | xcpretty -c
  - xcodebuild test -scheme CoreNetKitUnitTests -configuration "Debug" -sdk iphonesimulator -enableCodeCoverage YES -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.4' | xcpretty -c
addons:
  ssh_known_hosts: https://lastsprint.dev

after_success:
  - bash <(curl -s https://codecov.io/bash) -t b62fa427-b5d3-4318-885d-e7783e1d527c 
  - bash <(curl -s http://127.0.0.1:8811/shutdown)>
  - ssh-add ssh/id_rsa
  - ssh-add ssh/id_rsa.pub
  - ./deploy_docs.sh

